repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        args: [--severity=warning, --external-sources]
        exclude: "macos/zsh/.*"

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.0-1
    hooks:
      - id: shfmt
        args: [--write, --indent=2, --case-indent]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
